<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Schéma initial sur PostgreSQL : reprend l'état obtenu jusqu'ici par
 * doctrine:schema:update, désormais figé et versionné.
 */
final class Version20260729195710 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Schéma initial (PostgreSQL)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE ciqual_foods (code VARCHAR(20) NOT NULL, nom VARCHAR(255) NOT NULL, nom_norm VARCHAR(255) DEFAULT NULL, groupe VARCHAR(120) DEFAULT NULL, energie_kj DOUBLE PRECISION DEFAULT NULL, energie_kcal DOUBLE PRECISION DEFAULT NULL, proteines DOUBLE PRECISION DEFAULT NULL, glucides DOUBLE PRECISION DEFAULT NULL, lipides DOUBLE PRECISION DEFAULT NULL, sucres DOUBLE PRECISION DEFAULT NULL, ag_satures DOUBLE PRECISION DEFAULT NULL, sel DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE config_boutique (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_etablissement VARCHAR(150) NOT NULL, sous_titre VARCHAR(255) DEFAULT NULL, adresse VARCHAR(255) DEFAULT NULL, code_postal VARCHAR(10) DEFAULT NULL, ville VARCHAR(100) DEFAULT NULL, telephone VARCHAR(20) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, siret VARCHAR(50) DEFAULT NULL, logo_path VARCHAR(255) DEFAULT NULL, mention_pied TEXT DEFAULT NULL, tva_defaut NUMERIC(5, 2) NOT NULL, coef_defaut NUMERIC(10, 3) NOT NULL, taux_horaire_mo NUMERIC(10, 2) DEFAULT \'25.00\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE ingredient_categories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F498D05F5E237E06 ON ingredient_categories (name)');
        $this->addSql('CREATE TABLE ingredient_prices (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price_ht NUMERIC(10, 4) NOT NULL, supplier VARCHAR(200) DEFAULT NULL, effective_date DATE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ingredient_id INT NOT NULL, supplier_id INT DEFAULT NULL, purchase_invoice_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8B1AD18933FE08C ON ingredient_prices (ingredient_id)');
        $this->addSql('CREATE INDEX IDX_8B1AD182ADD6D8C ON ingredient_prices (supplier_id)');
        $this->addSql('CREATE INDEX IDX_8B1AD1825BAA637 ON ingredient_prices (purchase_invoice_id)');
        $this->addSql('CREATE TABLE ingredients (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, base_unit VARCHAR(20) NOT NULL, vat_rate NUMERIC(5, 2) NOT NULL, default_supplier VARCHAR(200) DEFAULT NULL, ciqual_code VARCHAR(20) DEFAULT NULL, ciqual_auto BOOLEAN DEFAULT false NOT NULL, unit_weight_g DOUBLE PRECISION DEFAULT NULL, allergens JSON DEFAULT NULL, traces JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4B60114F12469DE2 ON ingredients (category_id)');
        $this->addSql('CREATE TABLE invoice_ingredient_mappings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, invoice_label VARCHAR(500) NOT NULL, confirm_count INT NOT NULL, last_seen TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ingredient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_94D53A4B933FE08C ON invoice_ingredient_mappings (ingredient_id)');
        $this->addSql('CREATE INDEX idx_invoice_label ON invoice_ingredient_mappings (invoice_label)');
        $this->addSql('CREATE TABLE purchase_invoice_lines (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, supplier_ref VARCHAR(100) DEFAULT NULL, description VARCHAR(500) NOT NULL, qty NUMERIC(12, 4) NOT NULL, unit_code VARCHAR(10) NOT NULL, unit VARCHAR(20) NOT NULL, price_ht NUMERIC(10, 4) NOT NULL, vat_rate NUMERIC(5, 2) NOT NULL, line_total NUMERIC(12, 2) NOT NULL, invoice_id INT NOT NULL, ingredient_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A4C9653C2989F1FD ON purchase_invoice_lines (invoice_id)');
        $this->addSql('CREATE INDEX IDX_A4C9653C933FE08C ON purchase_invoice_lines (ingredient_id)');
        $this->addSql('CREATE TABLE purchase_invoices (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, invoice_id VARCHAR(100) NOT NULL, invoice_date DATE NOT NULL, total_ht NUMERIC(12, 2) DEFAULT NULL, total_ttc NUMERIC(12, 2) DEFAULT NULL, imported_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, supplier_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_43ED3CC72ADD6D8C ON purchase_invoices (supplier_id)');
        $this->addSql('CREATE TABLE recipe_cost_cache (computed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, material_cost_ht NUMERIC(10, 2) NOT NULL, total_cost_ht NUMERIC(10, 2) NOT NULL, cost_per_output_ht NUMERIC(10, 2) NOT NULL, advised_sell_ht NUMERIC(10, 2) NOT NULL, advised_sell_ttc NUMERIC(10, 2) NOT NULL, margin_ht NUMERIC(10, 2) NOT NULL, margin_percent NUMERIC(6, 2) NOT NULL, recipe_id INT NOT NULL, PRIMARY KEY (recipe_id))');
        $this->addSql('CREATE TABLE recipe_families (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EFCF9A525E237E06 ON recipe_families (name)');
        $this->addSql('CREATE TABLE recipe_lines (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, qty_brute NUMERIC(10, 4) NOT NULL, unit VARCHAR(20) NOT NULL, loss_percent NUMERIC(5, 2) NOT NULL, yield_percent NUMERIC(5, 2) NOT NULL, note TEXT DEFAULT NULL, sort_order INT NOT NULL, recipe_id INT NOT NULL, ingredient_id INT DEFAULT NULL, sub_recipe_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5912588959D8A214 ON recipe_lines (recipe_id)');
        $this->addSql('CREATE INDEX IDX_59125889933FE08C ON recipe_lines (ingredient_id)');
        $this->addSql('CREATE INDEX IDX_591258894BD5E4AA ON recipe_lines (sub_recipe_id)');
        $this->addSql('CREATE TABLE recipes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, family VARCHAR(100) NOT NULL, output_type VARCHAR(20) NOT NULL, output_value NUMERIC(10, 3) NOT NULL, loss_percent NUMERIC(5, 2) NOT NULL, yield_percent NUMERIC(5, 2) NOT NULL, product_vat_rate NUMERIC(5, 2) NOT NULL, labor_minutes INT DEFAULT 0 NOT NULL, labor_cost_ht NUMERIC(10, 2) NOT NULL, packaging_cost_ht NUMERIC(10, 2) NOT NULL, pricing_mode VARCHAR(20) NOT NULL, pricing_value NUMERIC(10, 3) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE suppliers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(300) NOT NULL, siret VARCHAR(20) DEFAULT NULL, vat_number VARCHAR(30) DEFAULT NULL, address_line VARCHAR(300) DEFAULT NULL, postcode VARCHAR(10) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, country VARCHAR(5) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_invoice_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AC28B95C26E94372 ON suppliers (siret)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(100) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9F85E0677 ON users (username)');
        $this->addSql('ALTER TABLE ingredient_prices ADD CONSTRAINT FK_8B1AD18933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredients (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ingredient_prices ADD CONSTRAINT FK_8B1AD182ADD6D8C FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ingredient_prices ADD CONSTRAINT FK_8B1AD1825BAA637 FOREIGN KEY (purchase_invoice_id) REFERENCES purchase_invoices (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ingredients ADD CONSTRAINT FK_4B60114F12469DE2 FOREIGN KEY (category_id) REFERENCES ingredient_categories (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice_ingredient_mappings ADD CONSTRAINT FK_94D53A4B933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredients (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_invoice_lines ADD CONSTRAINT FK_A4C9653C2989F1FD FOREIGN KEY (invoice_id) REFERENCES purchase_invoices (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_invoice_lines ADD CONSTRAINT FK_A4C9653C933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredients (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_invoices ADD CONSTRAINT FK_43ED3CC72ADD6D8C FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recipe_cost_cache ADD CONSTRAINT FK_53BB5B8059D8A214 FOREIGN KEY (recipe_id) REFERENCES recipes (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recipe_lines ADD CONSTRAINT FK_5912588959D8A214 FOREIGN KEY (recipe_id) REFERENCES recipes (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recipe_lines ADD CONSTRAINT FK_59125889933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredients (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recipe_lines ADD CONSTRAINT FK_591258894BD5E4AA FOREIGN KEY (sub_recipe_id) REFERENCES recipes (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ingredient_prices DROP CONSTRAINT FK_8B1AD18933FE08C');
        $this->addSql('ALTER TABLE ingredient_prices DROP CONSTRAINT FK_8B1AD182ADD6D8C');
        $this->addSql('ALTER TABLE ingredient_prices DROP CONSTRAINT FK_8B1AD1825BAA637');
        $this->addSql('ALTER TABLE ingredients DROP CONSTRAINT FK_4B60114F12469DE2');
        $this->addSql('ALTER TABLE invoice_ingredient_mappings DROP CONSTRAINT FK_94D53A4B933FE08C');
        $this->addSql('ALTER TABLE purchase_invoice_lines DROP CONSTRAINT FK_A4C9653C2989F1FD');
        $this->addSql('ALTER TABLE purchase_invoice_lines DROP CONSTRAINT FK_A4C9653C933FE08C');
        $this->addSql('ALTER TABLE purchase_invoices DROP CONSTRAINT FK_43ED3CC72ADD6D8C');
        $this->addSql('ALTER TABLE recipe_cost_cache DROP CONSTRAINT FK_53BB5B8059D8A214');
        $this->addSql('ALTER TABLE recipe_lines DROP CONSTRAINT FK_5912588959D8A214');
        $this->addSql('ALTER TABLE recipe_lines DROP CONSTRAINT FK_59125889933FE08C');
        $this->addSql('ALTER TABLE recipe_lines DROP CONSTRAINT FK_591258894BD5E4AA');
        $this->addSql('DROP TABLE ciqual_foods');
        $this->addSql('DROP TABLE config_boutique');
        $this->addSql('DROP TABLE ingredient_categories');
        $this->addSql('DROP TABLE ingredient_prices');
        $this->addSql('DROP TABLE ingredients');
        $this->addSql('DROP TABLE invoice_ingredient_mappings');
        $this->addSql('DROP TABLE purchase_invoice_lines');
        $this->addSql('DROP TABLE purchase_invoices');
        $this->addSql('DROP TABLE recipe_cost_cache');
        $this->addSql('DROP TABLE recipe_families');
        $this->addSql('DROP TABLE recipe_lines');
        $this->addSql('DROP TABLE recipes');
        $this->addSql('DROP TABLE suppliers');
        $this->addSql('DROP TABLE users');
    }
}
